
spring.application.name=workbloom
spring.datasource.url=jdbc:postgresql://localhost:5432/workbloom
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
n8n.wellness.webhook-url=http://127.0.0.1:5678/webhook/workbloom/wellness
# Disable Spring AI models for now
# Disable Spring AI auto-configuration
spring.ai.model.chat=none
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.embedding=none
spring.ai.model.image=none