spring.application.name=workbloom-backend
spring.application.name=workbloom
spring.datasource.url=jdbc:postgresql://localhost:5432/workbloom
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
spring.ai.openai.api-key=${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}