package com.workbloom.employee.serviceimpl;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.workbloom.employee.dto.CreateEmployeeRequest;
import com.workbloom.employee.entity.Employee;
import com.workbloom.employee.entity.EmployeeStatus;
import com.workbloom.employee.repository.EmployeeRepository;
import com.workbloom.exception.ConflictException;
import com.workbloom.exception.ResourceNotFoundException;

/**
 * User -> Employee bridge: resolution is by EMAIL (case-insensitive),
 * never by User id; provisioning is idempotent.
 */
@ExtendWith(MockitoExtension.class)
class EmployeeServiceImplProvisioningTest {

    @Mock
    private EmployeeRepository employeeRepository;

    private EmployeeServiceImpl service;

    @BeforeEach
    void setUp() {
        service = new EmployeeServiceImpl(employeeRepository);
    }

    @Test
    void getCurrentEmployee_resolvesByNormalizedEmail_notByUserId() {
        Employee employee = new Employee();
        employee.setId(37L); // deliberately different from any user id (e.g. 9)
        employee.setEmail("241129@iiitt.ac.in");

        when(employeeRepository.findByEmailIgnoreCase("241129@iiitt.ac.in"))
                .thenReturn(Optional.of(employee));

        Employee result = service.getCurrentEmployee("  241129@IIITT.AC.IN ");

        assertThat(result.getId()).isEqualTo(37L);
        verify(employeeRepository, never()).findById(any());
    }

    @Test
    void getCurrentEmployee_throwsClearErrorWhenNoProfile() {
        when(employeeRepository.findByEmailIgnoreCase("nobody@x.com"))
                .thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.getCurrentEmployee("nobody@x.com"))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    @Test
    void ensureEmployeeProfile_isIdempotentWhenProfileExists() {
        Employee existing = new Employee();
        existing.setId(37L);

        when(employeeRepository.findByEmailIgnoreCase("a@x.com"))
                .thenReturn(Optional.of(existing));

        Employee result = service.ensureEmployeeProfile("A@x.com", "Alice Smith");

        assertThat(result).isSameAs(existing);
        verify(employeeRepository, never()).save(any());
    }

    @Test
    void ensureEmployeeProfile_createsMinimalActiveProfileKeyedByEmail() {
        when(employeeRepository.findByEmailIgnoreCase("241129@iiitt.ac.in"))
                .thenReturn(Optional.empty());
        when(employeeRepository.existsByEmployeeCode(any())).thenReturn(false);
        when(employeeRepository.save(any(Employee.class)))
                .thenAnswer(inv -> inv.getArgument(0));

        service.ensureEmployeeProfile("241129@IIITT.AC.IN", "Test Student");

        ArgumentCaptor<Employee> captor = ArgumentCaptor.forClass(Employee.class);
        verify(employeeRepository).save(captor.capture());
        Employee saved = captor.getValue();

        assertThat(saved.getEmail()).isEqualTo("241129@iiitt.ac.in");
        assertThat(saved.getFirstName()).isEqualTo("Test");
        assertThat(saved.getLastName()).isEqualTo("Student");
        assertThat(saved.getStatus()).isEqualTo(EmployeeStatus.ACTIVE);
        assertThat(saved.getSalary()).isNull();
        assertThat(saved.getId()).isNull(); // id is generated by the database
    }

    @Test
    void createEmployee_rejectsDuplicateEmailIgnoringCase() {
        CreateEmployeeRequest request = new CreateEmployeeRequest();
        request.setFirstName("Dup");
        request.setEmail("Dup@X.com");

        when(employeeRepository.existsByEmailIgnoreCase("dup@x.com")).thenReturn(true);

        assertThatThrownBy(() -> service.createEmployee(request))
                .isInstanceOf(ConflictException.class);
        verify(employeeRepository, never()).save(any());
    }
}
